### ISSUE TITLE
STT0022: Fix issues in Pecha tools for STT/TTS

### ISSUE THREAD

**Issue by spsither** [OpenPecha/pecha-tools-for-stt#21]
### Description
The main platform for STT and TTS needs maintenance.

### Completion Criteria
Till the end of the STT/TTS project, Pecha tools for STT will need maintenance.

---
### Implementation Plan 
Supply the data pipeline and fix issues as they come up.

### Subtasks
 - [x] After 20 tasks the app gets stuck when assigning
 - [x] Make the audio speed sticky 
 - [x] After 20 tasks, one task gets  skipped from history
 - [x] Audio segmentation cuts in different end boundary

**Comment by spsither** [comment]
Error detected in audio segmentation function

**Comment by spsither** [comment]
✅ Fixed the audio segmentation function

**Comment by tentamdin** [comment]
@spsither if the task skipped from history is resolved then i think we can move it to test?
