### ISSUE TITLE
STT0026: add trashed minute column and total audio duration columns in stt report.

### ISSUE THREAD

**Issue by gangagyatso4364** [OpenPecha/pecha-tools-for-stt#22]
### Description
add trashed minute column using state = 'trashed' and add total audio duration 
total audio duration = reviewed minute + trashed minute
### Completion Criteria
a trashed min column and total audio duration showing minute for each user.
### Subtasks
- [x] create two new columns trashed min and total audio duration
- [x] add the sql query script to get trashed minute from database
- [x] fill the trashed min column and total audio duration using the above formula
