### ISSUE TITLE
Upload csv file feature

### ISSUE THREAD

**Issue by Karma-Tsering** [OpenPecha/pecha-tools-for-stt#25]
### Description

Add a feature to upload CSV files, allowing annotators to directly add task files instead of manually entering them.

### Subtask

- [x] Create new route 
- [x] UI to select file and upload
- [x] Parse csv file and add record into database

### Reviewer

- [x] @tentamdin

**Comment by Karma-Tsering** [comment]
@tentamdin the file you share has 32178 records and able to upload successfully

**Comment by tentamdin** [comment]
After discussion with Ganga, we had to update the default state to transcribing in db and handle the task id auto increment.

- [x] update default state to transcribing in db
- [x] handle id auto increment

**Comment by kaldan007** [comment]
@gangagyatso4364 the tool is ready to use. please update with objective owners
