### ISSUE TITLE
Discord Webhook for group Transcribing alert

### ISSUE THREAD

**Issue by TenzDelek** [OpenPecha/pecha-tools-for-stt#33]
Creating a webhook that sends alert in the specific discord channel when transcribing state data reaches less than 3000.

## task
- [x] setup Project
- [x] research on webhook, cron job and the project structure
- [x] implementing the webhook (pseudocode)
     - [x] creating endpoint
     - [x]  Prisma logic to secure the transcribing value
     - [x] conditional check whether it fall below 3000
     - [x] send alert if true
     - [x] error handling (trycatch)

## update after discussion with cho @tenkus47 
- [x] Logic change (no cron job but when user submit)
- [x] prisma queries update
- [x] test out the webhook
## reviewer
- [ ] @tentamdin  @tenkus47

**Comment by tenkus47** [comment]
Why do we need a cron job here? @TenzDelek

**Comment by TenzDelek** [comment]
> Why do we need a cron job here? @TenzDelek

did some research and got to know that we need a mechanism that monitor (hit the endpoint ) after a period of time. but not sure , let discuss it tomorrow in detail . usually some use setinterval. 
cc @tenkus47
