### ISSUE TITLE
[RFC0051] pecha.tools for STT

### ISSUE THREAD

**Issue by tentamdin** [OpenPecha/pecha-tools-for-stt#4]
## Work Planning

<details>
  <summary>Details</summary>

## Table of Contents

- [Housekeeping](#housekeeping)
- [Named Concepts](#named-concepts)
- [Summary](#summary)
- [Reference-Level Explanation](#reference-level-explanation)
- [Alternatives](#alternatives)
  * [Rationale](#rationale)
- [Drawbacks](#drawbacks)
- [Useful References](#useful-references)
- [Unresolved questions](#unresolved-questions)
- [Parts of the system affected](#parts-of-the-system-affected)
- [Future possibilities](#future-possibilities)
- [Infrastructure](#infrastructure)
- [Testing](#testing)
- [Documentation](#documentation)
- [Version History](#version-history)
- [Recordings](#recordings)
- [Work Phases](#work-phases)

## Housekeeping

*Please add ref in specified format into `RFC` title, e.g `[RFC9999]` if the corresponding RFW is `[RFW9999]`.*

*Please add into this `RFC` and related `PR's` titles `[RFC_id]` e.g `[RFC_9999]`.*

ALL BELOW FIELDS ARE REQUIRED

## Named Concepts

*Explain any new concepts introduced in this request.*

## Summary

*Explain in a Single paragraph what this request is about.*

## Reference-Level Explanation

*This section provides a detailed technical overview of the work. The design is explained with enough depth and detail to make it clear how:*

<em>

> The proposed changes interact with other systems (or other parts of the system that is changed)

> The actual implementation will take place

> Known challenges can be readily overcome

</em>

*This section includes practical examples and explains how this proposal makes those examples work.*

*This section becomes the engineering specification and work plan, so it must be sufficiently detailed to facilitate that.*

## Alternatives

*Confirm that alternative approaches have been evaluated and explain those alternatives briefly.*

### Rationale

> Why the currently proposed design was selected over alternatives?

> What would be the impact of going with one of the alternative approaches?

> Is the evaluation tentative, or is it recommended to use more time to evaluate different approaches?

## Drawbacks

*Describe any particular caveats and drawbacks that may arise from fulfilling this particular request?*

## Useful References

*Describe useful parallels and learnings from other requests, or work in previous projects.*

> What similar work have we already successfully completed?

> Is this something that has already been built by others?

> What other related learnings do we have?

> Are there useful academic literature or other articles related to this topic? (provide links)

> Have we built a relevant prototype previously?

> Do we have a rough mock for the UI/UX?

> Do we have a schematic for the system?

## Unresolved Questions

1. What is there that is unresolved (and will be resolved as part of fulfilling this request)?
dsd

> Are there other requests with same or similar problems to solve?

 
</em>

## Parts of the System Affected

<em>

- Which parts of the current system are affected by this request?
- What other open requests are closely related to this request?
- Does this request depend on the fulfillment of any other request?
- Does any other request depend on the fulfillment of this request?*

</em>
 
## Future possibilities

*How do you see the particular system or part of the system affected by this request being altered or extended in the future?*

## Infrastructure

*Describe the new infrastructure or changes in the current infrastructure required to fulfill this request.*

## Testing

*Describe the kind of testing procedures that are needed as part of fulfilling this request.*

## Documentation

*Describe the level of documentation fulfilling this request involves. Consider both end-user documentation and developer documentation.*

## Version History

*History of changes to this RFC. Following semantic versioning pattern and v0.1.2 for style.*

## Recordings

*Links to audio recordings of related discussion.*

</details>

 
## Work Phases

<h3 id="non-coding">Planning</h3>

*Keep original naming and structure, and keep it as the first section in the Work Phases section*

- [ ] RFC completed on: 
      Estimated time: 
      Actual time: 
- [ ] RFC reviewed and approved by: 
      Estimated time: 
      Actual time: 

<h3 id="implementation">Implementation</h3>

*A list of checkboxes, one per PR. Each PR should have a descriptive name that clearly illustrates what the work phase is about.*
- [x] #196
      Estimated time: 1hr
      Actual time: 
- [x] OpenPecha/pecha-tool-for-stt#3
      Estimated time: 1hr
      Actual time: 
- [x] OpenPecha/pecha-tool-for-stt#4
      Estimated time: 4hr
      Actual time: 
- [x] OpenPecha/pecha-tool-for-stt#5
      Estimated time: 1day
      Actual time: 
- [x] OpenPecha/pecha-tool-for-stt#6
      Estimated time: 6hr
      Actual time: 
- [x] OpenPecha/pecha-tool-for-stt#7
      Estimated time: 6hr
      Actual time: 
- [ ] OpenPecha/pecha-tool-for-stt#8
      Estimated time: 4hr
      Actual time: 
- [x] OpenPecha/pecha-tool-for-stt#15
      Estimated time: 2hr
      Actual time: 
- [x] OpenPecha/pecha-tools-for-stt#29
      Estimated time: 
      Actual time: 
- [x] OpenPecha/pecha-tools-for-stt#33
      Estimated time: 
      Actual time: 
- [ ] OpenPecha/pecha-tools-for-stt#38
      Estimated time: 
      Actual time: 
- [ ] OpenPecha/pecha-tools-for-stt#39
      Estimated time: 
      Actual time: 
- [ ] OpenPecha/pecha-tools-for-stt#40
      Estimated time: 
      Actual time: 
<h3 id="implementation">Completion</h3>

- [ ] Tested and approved by: @username, @username
      Estimated time: 
      Actual time: 
- [ ] Documentation approved @evanyerburgh
      Estimated time: 
      Actual time:
